### ISSUE TITLE
link highways aren't included in 'all roads'

### ISSUE THREAD

**Issue by JillisE** [chrstnbwnkl/zack-carto#4]
I've ran your application with all options set to maximum (all roads, waterways and places) on my hometown Amersfoort (NL).
The resulting svg doesn't include the motorway links at the junctions.
![Schermafbeelding 2022-09-14 112931](https://user-images.githubusercontent.com/68056422/190117435-d4a927eb-17fe-4037-bc6f-eaa2219d2d58.jpg)

**Comment by chrstnbwnkl** [comment]
Thanks for opening an issue! I was able to reproduce it, turns out I forgot to add _link tags entirely.
